# Generated by Django 4.1.7 on 2023-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('isbn', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('edition', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('pdf', models.FileField(null=True, upload_to='uploads')),
                ('image', models.ImageField(null=True, upload_to='uploads')),
            ],
        ),
    ]
